
# Site settings
# 站点名字，也就是html的title 会显示在浏览器标签上。
title: 马学俊
#name: 马学俊
# 站点副标题，会显示在首页上，可以不填。
subtitle: 博后
email: yinuoyumi@163.com
# 站点描述，可以不填
description: 

baseurl: ""
url: "https://stamax360.github.io"
github_username:  stamax360
disqus_baseurl: "https://stamax360.github.io/"
disqus_shortname: https://stamax360.github.io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "马学俊"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: pesoto
    url:https://github.com/stamax360/stamax360.github.io/
    desc: Fork me on GitHub
    share: false

  - name: NUS
    icon: NUS
    username: NUS
    url: http://www.nus.edu.sg/
    desc: Connect with me on LinkedIn
    share: true
